Repository setup eric
Cascadia-Connections/photo-points pull request #10
Opened 2019-04-17 02:02 UTC by Ro914

Temporary, placeholder models were used. Code needs to incorporate Willie's entity models after his branch is merged to the develop branch.

2019-04-19 21:38 UTC, sruble reviewed
looks good to me Eric.

2019-04-22 18:14 UTC, weberwilliamb requested changes

2019-04-22 18:14 UTC, weberwilliamb commented on photo-points/Models/SeedData.cs
> +namespace photo_points.Models
I noticed that you hadn't updated with our entity model we merged last week.

2019-04-30 06:16 UTC, MaxIgnatyev approved these changes
Looks good to me.

2019-05-06 03:51 UTC, weberwilliamb approved these changes
I'm not seeing any issues.

2019-05-06 19:58 UTC, MaxIgnatyev approved these changes
Looks good

2019-05-06 19:58 UTC, sruble approved these changes
Looks good Eric

2019-05-06 20:06 UTC, Sara-webaplication approved these changes

2019-05-06 20:06 UTC, Sara-webaplication commented on photo-points/Models/ApplicationDbContext.cs
> +}
looks ok

2019-05-06 20:06 UTC, sansari246 commented
I approved it.

2019-05-06 20:22 UTC, merged