add tag on details
Cascadia-Connections/photo-points pull request #104
Opened 2020-05-06 06:53 UTC by floydfix

closes #91

2020-05-07 23:09 UTC, NathanaelRorberg requested changes
I can see the tags, and delete tags, but I can't add a tag. The little window opens and I can write in it but I can't apply it.

2020-05-08 03:57 UTC, floydfix commented
> 
> 
> I can see the tags, and delete tags, but I can't add a tag. The little window opens and I can write in it but I can't apply it.

It only allows you to add pre authorized tags, that will autocomplete. the list right now is one, two, three, four

2020-05-08 06:26 UTC, NathanaelRorberg approved these changes

2020-05-08 08:20 UTC, taerichard approved these changes
Nice looks awesome

2020-05-09 04:04 UTC, gjesionowski approved these changes

2020-05-09 06:59 UTC, AlainNshimirimana approved these changes

2020-05-11 04:52 UTC, merged