Ienumerables sim#41
Cascadia-Connections/photo-points pull request #53
Opened 2019-06-04 09:07 UTC by sruble

I've added the foreach loop in the controller, as well as one in the Pending view page. They are currently incomplete, but I was wondering if I'm on the right track.

2019-06-05 01:35 UTC, MaxIgnatyev reviewed
That is what I've been trying to do so far, similar to the LuckySpin example. I think the ViewModel has to be build out to support it better.

2019-06-05 17:34 UTC, Bansenauer-Cascadia reviewed
A good start on the setup; more work needed to populate the ViewModel with the photo data

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points.Tests/AdminApprovalServiceTests.cs
> +//======= // //not sure if this line of code was important
Yes - the services use the repositories to access the model data.

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +        public AdminController(IAdminReviewServices adminServiceReview)
Perfect

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +            IEnumerable<Capture> pendingImages = _adminReviewServices.GetUnapprovedCaptures();
This looks good, though your variable name would be clearer if you called it "pendingCaptures" instead of "pendingImages"

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +            foreach (Capture img in pendingImages) // looking at comments on line 18 and 23 in Capture.cs // should we display all images since they are the default?
You are correctly using the foreach loop to go through the Captures ( again, I suggest you call each item a "capture" rather than an "img"

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +            {
Inside the loop, your work is to take each capture's photo data and convert it into a base64 string, then store it in your ViewModel as a collection of strings  `List<String>`

2019-06-05 17:34 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
Once you have filled your ViewModel with the data, then you can pass it to your view as an IEnumerable

2019-06-05 19:10 UTC, Sara-webaplication approved these changes
looks perfect to me,

2019-06-05 19:39 UTC, weberwilliamb approved these changes
Looks Good!

2019-06-06 22:43 UTC, MaxIgnatyev commented on photo_points/Views/Admin/PhotoStream.cshtml
> +<div class="container card-body-sm">
For now I would suggest using a for loop as Brian said to display these, see my branch (just updated).

2019-06-08 01:12 UTC, Bansenauer-Cascadia requested changes

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points.Tests/AdminApprovalServiceTests.cs
> +//======= // //not sure if this line of code was important
Sim, I think I understand your question about the importance of the "line of code"

The lines 4, 6, and 8 are part of the way Git marks merge conflicts in the code and should be deleted once you a merge is finished. It looks like they got left in by mistake.

`<<<<<<< HEAD` marks the beginning of a merge conflict. It is followed by the lines of code the current branch (in this case line 5).

`======= ` separates the current branch code (line 5) from the merged branch code (line 7)

`>>>>>>> be76c438347a37c0012ee223681792bd372510f5` marks the end of the merge. The string of characters at the end is the hexidecimal value of the merged branch's tag.

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points.Tests/AdminApprovalServiceTests.cs
> +//======= // //not sure if this line of code was important
Since lines 4, 6, and 8 should be removed, and since line 5 and 7 are functionally identical, you should replace lines 4-8 with a single line
`using photo_points.Repositories;`

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +                    string mimeType = capture.photo;
The mimeType can be a hard-coded string (text surrounded by double quotes) representing the type of image. Common examples for photos are "image/jpeg" or "image/png" depending on what type of image file it is. 
BTW: it looks like Sara is using all JPEG images in her fake repo.

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +                    List<string> base64 = Convert.ToBase64String(capture.photo);
This is pretty close, but you are mixing up when to use the List<string> and when to use a single string.
In this line, you are inside the loop and working with individual capture objects that have a single string in their `capture.photo` property. So use a **string** instead of the **List<string>**

`string base64 = Convert.ToBase64String(capture.photo)`

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +                      pvm = base64;
You are missing a step and have an error in line 75. 

Inside the loop you have to get the base64 string from each capture (you are doing this in line 72 - edited), then adjust its format (you have this commented out in line 73), and then you need to **add** it to the PendingViewModel's list of strings. (not just assign it to the pvm as currently incorrect in line 75 )

Remember, your PendingViewModel instance (`pvm`) has a List of strings property called _ImageSource_  which you can reference using
`pvm.ImageSource`
Also remember that every List has an **add** method, in this case one that takes a string, so you can do
`pvm.ImageSource.Add(   _your formatted image string here_ )`

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +                return View("Pending", pvm);
You should wait till the loop has completed adding all the capture photos before going to the view. 
Move line 76 down to replace line 80 (outside the loop).

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Controllers/AdminController.cs
> +        // // whould this be followed by a GetEnumerator?
No, the return statement will end the Action. Using the Enumerator can happen in your cshtml view.

2019-06-08 01:12 UTC, Bansenauer-Cascadia commented on photo_points/Views/Admin/Pending.cshtml
> +        <img src="mimeSource"/>
This code will display the image, but you likely want to put one entire `<div>` for the card inside your loop with the image source replaced, like

```
<div class="container card-body-sm">
    <div class="row">
        <img class="card-img-sm" src="mimeSource" />
    </div>
    <div class="row card-sm-content">
        <h3>Photopoint Name</h3>
        <div class="col-sm-10">
            <div class="row">
                <h6>Jan 15, 2013</h6>
            </div>
            <div class="row">
                <h6>User1</h6>
            </div>
        </div>
        <div class="col-sm-2">
            <span class="circle"></span>
        </div>
    </div>
</div>
```
Then the loop will create a card `<div>` for each image in the ViewModel

2019-06-10 18:44 UTC, RoEric approved these changes
Needs to pull latest version of the develop since I just merged my branched with it. Other than that, I don't see any issues with the work you did.

2019-06-10 23:21 UTC, merged