Closes #72
Cascadia-Connections/photo-points pull request #75
Opened 2020-04-18 22:26 UTC by AlainNshimirimana

After many tries and errors, I finally managed to create a database and an initial migration.
I put everything under the "database-feature-Alain" branch.
Please take a look at it and let me know what needs to be changed

2020-04-18 23:00 UTC, NathanaelRorberg commented
I can see the migrations but I can't seem to find the database in the sql server object explorer window. What's the name of the database?

2020-04-18 23:02 UTC, NathanaelRorberg requested changes
I can see the migrations but I can't seem to find the database in the sql server object explorer window. What's the name of the database?

2020-04-19 00:51 UTC, AlainNshimirimana commented
Nathan, the database is called AdminService. If you can't find it, try the following.
1. dotnet ef database drop
2. dotnet ef database update
3. Build solution and run the app
4. Check sql server explorer again

2020-04-19 01:37 UTC, floydfix reviewed
Also, un-comment line 16 in PhotoDataContext.cs and the db will create the first time run.
Meant to request these as changes.

2020-04-19 01:37 UTC, floydfix commented on photo_points/Startup.cs
> +                //options.UseSqlite(Configuration.GetConnectionString("IndyBooks-Mac-Sqlite"));
And this

2020-04-19 01:37 UTC, floydfix commented on photo_points/Models/Tag.cs
> +        //public ICollection<Capture> captures { get; set; }
You should delete this commented code

2020-04-19 01:42 UTC, AlainNshimirimana commented on photo_points/Models/Tag.cs
> +        //public ICollection<Capture> captures { get; set; }
Yep. Done.

2020-04-19 01:55 UTC, floydfix approved these changes
Sorry, I guess you need to have some more code that calls this PhotoDataContext class to get that to auto build the Database. I am not sure it is totally needed at this point since the next bit we do with the db should be to hook it  up and that will call the ensureCreated code.

2020-04-19 02:03 UTC, taerichard reviewed
I was told it's best practice to capitalize the first letter of public fields on a class.  And lowercase first letter on private fields.

2020-04-19 07:19 UTC, taerichard approved these changes

2020-04-20 06:11 UTC, gjesionowski approved these changes

2020-04-20 19:54 UTC, NathanaelRorberg approved these changes

2020-04-20 20:55 UTC, closed without merging