Closes #67
Cascadia-Connections/photo-points pull request #82
Opened 2020-04-25 02:23 UTC by NathanaelRorberg

The database is populated with dummy User Info.

2020-04-25 02:53 UTC, AlainNshimirimana requested changes
It looks like you're still using the 2.1.1 version of the project. It would be great if updated it to the 3.1.0 version. 
The current develop branch is the 3.1 version and it has the database created. All you would need to do is add the dummy data and the code that you created to that version. Hopefully that might help get rid of the conflicts. 
I don't know if that made sense

2020-04-25 02:59 UTC, gjesionowski commented
Like Alain said, working from the latest version of develop sounds like a good idea to get rid of conflicts

2020-04-25 03:02 UTC, NathanaelRorberg commented
Thanks for catching that. I think the latest push will fix that.

2020-04-25 03:08 UTC, AlainNshimirimana approved these changes

2020-04-25 03:48 UTC, gjesionowski approved these changes

2020-04-25 04:41 UTC, floydfix approved these changes

2020-04-26 21:42 UTC, taerichard approved these changes

2020-04-26 22:01 UTC, merged