created AdminReviewRepo with defined methods, created IAdminReviewRep…
Cascadia-Connections/photo-points pull request #96
Opened 2020-05-01 05:07 UTC by taerichard

…o that contains the signature only

2020-05-01 05:10 UTC, taerichard commented
This is the IAdminReviewRepo file that will be used in the controllers.    

    // knows about the dbcontext issue 88
    public interface IAdminReviewRepository 
    {
        IEnumerable<Capture> GetCaptures();
        Capture GetCapture(long captureId);
        IEnumerable<Capture> GetAllUnapproved();
        Capture UpdateCapture(Capture capture);
        Capture DeleteCapture(long captureId);
        void SaveChanges(Capture capt);
    }
`

2020-05-01 06:17 UTC, taerichard commented on photo_points/Repositories/AdminReviewRepository.cs
> +        public void SaveChanges(Capture capt)
this is the update part after fixing the details of the capture

2020-05-01 06:18 UTC, taerichard commented on photo_points/Repositories/AdminReviewRepository.cs
> +                _dbcontext.Captures.Remove(captureToDelete);
+ save changes

2020-05-02 02:27 UTC, floydfix requested changes
Does not build. Error in the new AdminReviewRepository. When you fix that, remove the FakeAdminReviewRepository and change any remaining calls from it to your new AdminReviewRepository, and make sure it all still works

2020-05-03 07:12 UTC, taerichard commented
No error with build now.  Created Test Capture action in admin controller to check if it works.  Seems fine, just need capture data populated.

2020-05-04 00:59 UTC, gjesionowski requested changes

2020-05-04 00:59 UTC, gjesionowski commented on photo_points/Controllers/AdminController.cs
> -        public AdminController(IAdminReviewServices adminServiceReview, PhotoDataContext dbc)
The second part of the old line 23 "public AdminController(IAdminReviewServices adminServiceReview**, PhotoDataContext dbc**)" being removed seems to cause an issue with changing pages to pages that use the database

2020-05-04 01:04 UTC, gjesionowski commented on photo_points/Controllers/AdminController.cs
> -        public AdminController(IAdminReviewServices adminServiceReview, PhotoDataContext dbc)
Yah tested on my machine and replacing the new line 22 with this should fix it
`AdminController(IAdminReviewRepository adminReviewRepo, PhotoDataContext dbc)
        {
            _adminReviewRepo = adminReviewRepo;
            _dbc = dbc;
        }`

2020-05-04 04:06 UTC, closed without merging