5 richard
Cascadia-Connections/photo-points pull request #98
Opened 2020-05-04 04:07 UTC by taerichard

#96

2020-05-04 19:46 UTC, NathanaelRorberg approved these changes
Looks good. I don't get any errors.

2020-05-04 21:45 UTC, floydfix requested changes

2020-05-04 21:45 UTC, floydfix commented on photo_points/Repositories/AdminReviewRepository.cs
> +        public List<Capture> repo = new List<Capture> {
This fake data can be removed now that we are populating the db with other fake data, but you should also make sure that all of the same things are entered in the db somehow

2020-05-04 21:45 UTC, floydfix commented on photo_points/Repositories/AdminReviewRepository.cs
> +        public void SaveChanges(Capture capt)
since the fake data in var repo will be gone, make sure this saves into the db

2020-05-04 21:45 UTC, floydfix commented on photo_points/Repositories/FakeAdminReviewRepository.cs
> +/*
Get rid of this file and all references to it

2020-05-04 21:45 UTC, floydfix commented on photo_points/Controllers/AdminController.cs
> +using photo_points.Repositories;
remove unused imports

2020-05-04 21:45 UTC, floydfix commented on photo_points/Startup.cs
> +            //if (env.EnvironmentName == "development")
remove commented unused code

2020-05-07 06:22 UTC, floydfix requested changes
Almost. Can you make sure the seed database code add tags (doesnt matter what they are named) and captures that use (all the same picture, use code from fake repo, and tags and users created earlier in the seed database code)
You need to leave the operation of the site the same as when you started, so we can still browse to all pages and get some sort of result to work with

2020-05-08 20:41 UTC, NathanaelRorberg requested changes
I get this error when I run the application: InvalidOperationException: The seed entity for entity type 'Capture' cannot be added because the value '1' provided for the property 'captureID' is not of the type 'long'.

Don't forget test the application before you push.

2020-05-08 21:20 UTC, taerichard commented
Thanks and yeah still trying to figure it out.

2020-05-11 01:52 UTC, NathanaelRorberg approved these changes
Looks good to me.

2020-05-11 18:35 UTC, NathanaelRorberg requested changes
error when opening the Pending page: NullReferenceException: Object reference not set to an instance of an object.

2020-05-13 18:00 UTC, gjesionowski commented
I was seeing the same thing as Nathanael

2020-05-19 00:06 UTC, floydfix approved these changes

2020-05-19 00:09 UTC, NathanaelRorberg approved these changes

2020-05-19 00:16 UTC, gjesionowski approved these changes

2020-05-19 05:04 UTC, AlainNshimirimana approved these changes

2020-05-27 19:06 UTC, merged